server:
  type: simple
  rootPath: /api/
  applicationContextPath: /tastysearch
  adminContextPath: /admin
  connector:
    type: http
    port: 80

#metrics:
#  reporters:
#    - type: <type>
#      durationUnit: milliseconds
#      rateUnit: seconds
#      excludes: (none)
#      includes: (all)
#      frequency: 1 second

sampleSize: 100000
resultSize: 20
fileName: "foods.txt"
