server:
  type: simple
  rootPath: /api/
  applicationContextPath: /tastysearch
  adminContextPath: /admin
  connector:
    type: http
    port: 9001

# number of samples to collect out of all the reviews
sampleSize: 100000

# number of results to emit
resultSize: 20

# name of the data file
fileName: "foods.txt"

# number of queries to generate for load test
testSetSize: 100000

# max number of tokens in the generated query (for load test)
maxTestTokens: 10

# name of the test set file
testSetFileName: "testset.csv"
